version: '3.8'

services:
  python-sidecar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-sidecar
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload 