version: '3.8'

services:
  python-sidecar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-sidecar
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload 