name: Python Sidecar CI/CD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test with pytest
      run: |
        python -m pytest
        
    - name: Make scripts executable
      run: |
        chmod +x restart_server.sh kill_server.sh e2e_test.sh verify_server_is_running.sh
        
    - name: Start server and run end-to-end tests
      run: |
        nohup uvicorn app.main:app --host 0.0.0.0 --port 5000 &
        ./verify_server_is_running.sh
        CI=true ./e2e_test.sh

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: python-sidecar:latest
        
    - name: Test Docker image
      run: |
        # Start the Docker container
        docker run --rm -d -p 5000:5000 --name test-container python-sidecar:latest
        
        # Verify server is running
        ./verify_server_is_running.sh
